name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'

      - uses: ko-build/setup-ko@v0.7
      - name: Build and push Docker images using ko
        run: ko build --base-import-paths --platform=linux/amd64,linux/arm64 --push ./cmd/refinery
        env:
          GOFLAGS: "-ldflags=-X=main.BuildID=${{ github.ref_name }}"
